### ISSUE TITLE
Error when trying to validate RUC since today

### ISSUE THREAD

**Issue by augustosamame** [odoope/l10n_pe#5]
Hello. Since today, I am getting the following Odoo error when trying to validate a RUC number:
It happens with several (valid) RUC number I have tried with.

Traceback (most recent call last):
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-10.0/addons/web/controllers/main.py", line 862, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo-10.0/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo-10.0/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo-10.0/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/models.py", line 5460, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/opt/odoo/odoo-10.0/odoo/models.py", line 5358, in _onchange_eval
    method_res = method(self)
  File "/opt/odoo/odoo-10.0/addons/odoope_ruc_validation/models/res_partner.py", line 148, in vat_change
    consuta, captcha_val= self._get_captcha(vat_type)
  File "/opt/odoo/odoo-10.0/addons/odoope_ruc_validation/models/res_partner.py", line 48, in _get_captcha
    img=Image.open(StringIO.StringIO(r.content))
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 2295, in open
    % (filename if filename else fp))
IOError: cannot identify image file <StringIO.StringIO instance at 0x7feaa235bb00>

**Comment by soluxSG** [comment]
El error es del dominio py-devs.com. Parece que la api no sigue disponible. Es una pena
